### PR TITLE
Revival of the Docs page

### PR DESCRIPTION
**Pull request by bluong**
Other than a few quirks, the docs page is back!

### CODE REVIEW

**Comment by jtlan** [comment]
What are the quirks? Can we get some tickets for visibility?

**Comment by jtlan** [comment]
Every definition shows
"Defined in /Users/bluong/git/plottable-website/plottable.d.ts" at the bottom -- is there a way to hide that?

**Comment by jtlan** [comment]
Nice, this new version shows inherited methods.

**Comment by rcchen** [comment]
Well, for one, "d3" at the top of the right column 404s at http://localhost:4000/docs/modules/_d3_.html

**Comment by bluong** [comment]
One of the instant quirks I found was the thing @rcchen found.  I'm not sure if this is true, but I believe that if you start a document with an underscore, it doesn't play well in URL land?  The file definitely exists in the directory, it's just not being served to the browser :/

Also, I think technically that path shouldn't need to exist?

**Comment by bluong** [comment]
@jtlan Not sure if this is 100% true, but so far I cannot seem to find documentation on the private methods.  I'm unsure if it's because there's no jsdoc on them, or it's because they don't exist in the typings file.  Protected methods and such exist however, and yes I would like to hide them (preferably I want to hide the underscored functions too but I think that's really project-specfic to us to do)

**Comment by bluong** [comment]
Mostly noting that this is mainly a third-party enhancement with the only changes on my end being some changes to the script to generate the docs.  We probably want to get this in ASAP and then iteratively either work with Typedoc to make the docs better, use our own themes/styliings to make our own docs better, or think of possibly a first-party solution.

**Comment by jtlan** [comment]
Agreed. I think we should merge this, then file tickets to clean up the stylings, etc.

No real problems with this.

**Pull request merged**
